=== Dragan2402/xml-veb-servisi/p1-backend/src/main/resources/data/schemas/p1_schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
    targetNamespace="http://euprava.com/p1/model" xmlns:p1="http://euprava.com/p1/model">
    <xs:element name="Obrazac_P1">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="p1:Popunjava_zavod"/>
                <xs:element ref="p1:Zahtev_za_priznanje_patenta"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="Popunjava_zavod">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Broj_prijave" type="xs:string"> </xs:element>
                <xs:element name="Datum_prijema" type="xs:date"/>
                <xs:element name="Priznati_datum_podnosenja" type="xs:date"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="Zahtev_za_priznanje_patenta">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="p1:Naziv_pronalaska"/>
                <xs:element name="Podnosilac" type="p1:TPodnosilac"/>
                <xs:element minOccurs="0" name="Pronalazac" type="p1:TPronalazac"/>
                <xs:element minOccurs="0" name="Punomocnik" type="p1:TPunomocnik"/>
                <xs:element minOccurs="0" name="Adresa_za_dostavljanje" type="p1:TAdresa"/>
                <xs:element name="Nacin_dostavljanja" type="p1:TNacin_dostavljanja"/>
                <xs:element minOccurs="0" ref="p1:Povezana_prijava"/>
                <xs:element minOccurs="0" ref="p1:Zahtev_za_priznanje_prava_prvenstva"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="Naziv_pronalaska">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Na_srpskom" type="xs:string"/>
                <xs:element name="Na_engleskom" type="xs:string"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="Povezana_prijava">
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="p1:TPrijava">
                    <xs:attribute name="tip" type="p1:TTip_povezane_prijave" use="required"/>
                </xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>
    <xs:element name="Zahtev_za_priznanje_prava_prvenstva">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" minOccurs="1" ref="p1:Ranija_prijava"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="Ranija_prijava">
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="p1:TPrijava">
                    <xs:attribute name="oznaka_drzave" use="required">
                        <xs:simpleType>
                            <xs:restriction base="xs:string">
                                <xs:pattern value="[A-Z][A-Z]"/>
                            </xs:restriction>
                        </xs:simpleType>
                    </xs:attribute>
                </xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="TAdresa">
        <xs:sequence>
            <xs:element name="Ulica" type="xs:string"/>
            <xs:element name="Broj" type="xs:positiveInteger"/>
            <xs:element name="Postanski_broj">
                <xs:simpleType>
                    <xs:restriction base="xs:positiveInteger">
                        <xs:minInclusive value="11000"/>
                        <xs:maxInclusive value="40000"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="Mesto" type="xs:string"/>
            <xs:element minOccurs="0" name="Drzava" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TKontakt">
        <xs:sequence>
            <xs:element name="Broj_telefona" type="xs:string"/>
            <xs:element name="E_posta" type="xs:string"/>
            <xs:element minOccurs="0" name="Broj_faksa" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType abstract="true" name="TLice">
        <xs:sequence>
            <xs:element name="Adresa" type="p1:TAdresa"/>
            <xs:element name="Kontakt" type="p1:TKontakt"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType abstract="true" name="TPodnosilac">
        <xs:complexContent>
            <xs:extension base="p1:TLice">
                <xs:attribute name="pronalazac" type="xs:boolean" use="required"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="TFizicki_podnosilac">
        <xs:complexContent>
            <xs:extension base="p1:TPodnosilac">
                <xs:sequence>
                    <xs:element name="Ime" type="xs:string"/>
                    <xs:element name="Prezime">
                        <xs:simpleType>
                            <xs:restriction base="xs:string">
                                <xs:pattern value="[A-ZŠĐČĆŽ]+"/>
                            </xs:restriction>
                        </xs:simpleType>
                    </xs:element>
                    <xs:element name="Drzavljanstvo" type="xs:string"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="TPravni_podnosilac">
        <xs:complexContent>
            <xs:extension base="p1:TPodnosilac">
                <xs:sequence>
                    <xs:element name="Poslovno_ime">
                        <xs:simpleType>
                            <xs:restriction base="xs:string">
                                <xs:pattern value="[A-ZŠĐČĆŽ ]+"/>
                            </xs:restriction>
                        </xs:simpleType>
                    </xs:element>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="TPronalazac">
        <xs:complexContent>
            <xs:extension base="p1:TLice">
                <xs:sequence>
                    <xs:element name="Ime" type="xs:string"/>
                    <xs:element name="Prezime">
                        <xs:simpleType>
                            <xs:restriction base="xs:string">
                                <xs:pattern value="[A-ZŠĐČĆŽ]+"/>
                            </xs:restriction>
                        </xs:simpleType>
                    </xs:element>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType abstract="true" name="TPunomocnik">
        <xs:complexContent>
            <xs:extension base="p1:TLice">
                <xs:attribute name="tip" type="p1:TTip_punomocnika" use="required"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="TFizicki_punomocnik">
        <xs:complexContent>
            <xs:extension base="p1:TPunomocnik">
                <xs:sequence>
                    <xs:element name="Ime" type="xs:string"/>
                    <xs:element name="Prezime">
                        <xs:simpleType>
                            <xs:restriction base="xs:string">
                                <xs:pattern value="[A-ZŠĐČĆŽ]+"/>
                            </xs:restriction>
                        </xs:simpleType>
                    </xs:element>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="TPravni_punomocnik">
        <xs:complexContent>
            <xs:extension base="p1:TPunomocnik">
                <xs:sequence>
                    <xs:element name="Poslovno_ime">
                        <xs:simpleType>
                            <xs:restriction base="xs:string">
                                <xs:pattern value="[A-ZŠĐČĆŽ ]+"/>
                            </xs:restriction>
                        </xs:simpleType>
                    </xs:element>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="TPrijava">
        <xs:sequence>
            <xs:element name="Broj_prijave">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value="[1-9]\d*\/\d{2}"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="Datum_podnosenja" type="xs:date"/>
        </xs:sequence>
    </xs:complexType>
    <xs:simpleType name="TTip_punomocnika">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Punomocnik_za_zastupanje"/>
            <xs:enumeration value="Punomocnik_za_prijem_pismena"/>
            <xs:enumeration value="Zajednicki_predstavnik"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="TNacin_dostavljanja">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Elektronska_forma"/>
            <xs:enumeration value="Papirna_forma"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="TTip_povezane_prijave">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Dopunska_prijava"/>
            <xs:enumeration value="Izdvojena_prijava"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== Dragan2402/xml-veb-servisi/p1-backend/src/main/resources/data/documents/p1_example.xml
<?xml version="1.0" encoding="UTF-8"?>
<Obrazac_P1 xmlns="http://p1.euprava.com/model"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://p1.euprava.com/model ../schemas/p1_schema.xsd">
    <Popunjava_zavod>
        <Broj_prijave>1/23</Broj_prijave>
        <Datum_prijema>2023-01-19</Datum_prijema>
        <Priznati_datum_podnosenja>2023-01-19</Priznati_datum_podnosenja>
    </Popunjava_zavod>
    <Zahtev_za_priznanje_patenta>
        <Naziv_pronalaska>
            <Na_srpskom>Automatski sistemi kočenja</Na_srpskom>
            <Na_engleskom>Autonomous braking system</Na_engleskom>
        </Naziv_pronalaska>
        <Podnosilac pronalazac="false" xsi:type="TPravni_podnosilac">
            <Adresa>
                <Ulica>Glavna</Ulica>
                <Broj>23</Broj>
                <Postanski_broj>11080</Postanski_broj>
                <Mesto>Zemun</Mesto>
                <Drzava>Srbija</Drzava>
            </Adresa>
            <Kontakt>
                <Broj_telefona>011/2194-492</Broj_telefona>
                <E_posta>br_assistant@gmail.com</E_posta>
                <Broj_faksa>011/2194-492</Broj_faksa>
            </Kontakt>
            <Poslovno_ime>BRAKING ASSISTANT</Poslovno_ime>
        </Podnosilac>
        <Pronalazac>
            <Adresa>
                <Ulica>4. Sremski Bataljon</Ulica>
                <Broj>10</Broj>
                <Postanski_broj>11080</Postanski_broj>
                <Mesto>Zemun</Mesto>
                <Drzava>Srbija</Drzava>
            </Adresa>
            <Kontakt>
                <Broj_telefona>066/936-8575</Broj_telefona>
                <E_posta>dilic@gmail.com</E_posta>
            </Kontakt>
            <Ime>Dragutin</Ime>
            <Prezime>ILIĆ</Prezime>
        </Pronalazac>
        <Punomocnik tip="Punomocnik_za_prijem_pismena" xsi:type="TFizicki_punomocnik">
            <Adresa>
                <Ulica>4. Sremski bataljon</Ulica>
                <Broj>6</Broj>
                <Postanski_broj>11080</Postanski_broj>
                <Mesto>Zemun</Mesto>
            </Adresa>
            <Kontakt>
                <Broj_telefona>066/936-8581</Broj_telefona>
                <E_posta>jovanr@gmail.com</E_posta>
            </Kontakt>
            <Ime>Jovan</Ime>
            <Prezime>RAJAČIĆ</Prezime>
        </Punomocnik>
        <Nacin_dostavljanja>Papirna_forma</Nacin_dostavljanja>
        <Povezana_prijava tip="Dopunska_prijava">
            <Broj_prijave>1/22</Broj_prijave>
            <Datum_podnosenja>2022-01-10</Datum_podnosenja>
        </Povezana_prijava>
        <Zahtev_za_priznanje_prava_prvenstva>
            <Ranija_prijava oznaka_drzave="RS">
                <Broj_prijave>3/22</Broj_prijave>
                <Datum_podnosenja>2022-12-12</Datum_podnosenja>
            </Ranija_prijava>
            <Ranija_prijava oznaka_drzave="RS">
                <Broj_prijave>4/21</Broj_prijave>
                <Datum_podnosenja>2021-12-12</Datum_podnosenja>
            </Ranija_prijava>
        </Zahtev_za_priznanje_prava_prvenstva>
    </Zahtev_za_priznanje_patenta>
</Obrazac_P1>
