=== Dragan2402/xml-veb-servisi/a1-backend/src/main/resources/data/schemas/a1_shema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
           targetNamespace="http://euprava.rs/a1" xmlns:a1="http://euprava.rs/a1">

    <xs:element name="obrazacA1">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="1" name="id">
                    <xs:simpleType>
                        <xs:restriction base="xs:long">
                            <xs:minInclusive value="1"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="Podnosilac" type="a1:TPodnosilac"/>
                <xs:element maxOccurs="1" minOccurs="0" name="Pseudonim_Znak_Autora"
                            type="xs:string"/>
                <xs:element minOccurs="0" name="Punomocnik" type="a1:TOsoba"/>
                <xs:element name="Djelo" type="a1:TDjelo"/>
                <xs:element name="Potpis" type="xs:string"/>
                <xs:element minOccurs="0" name="Sifra_Opisa" type="xs:string"/>
                <xs:element minOccurs="0" name="Sifra_Primjera" type="xs:string"/>
                <xs:element name="Broj_Prijave" type="xs:positiveInteger"/>
                <xs:element name="Datum_Podnosenja" type="xs:date"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:complexType abstract="true" name="TPodnosilac">
        <xs:sequence>
            <xs:element name="Telefon" type="a1:TBrojTelefona"/>
            <xs:element name="Email" type="a1:TEmail"></xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TFizicki_Podnosilac">
        <xs:complexContent>
            <xs:extension base="a1:TPodnosilac">
                <xs:sequence>
                    <xs:element name="Podaci_Osoba" type="a1:TOsoba"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="TPravni_Podnosilac">
        <xs:complexContent>
            <xs:extension base="a1:TPodnosilac">
                <xs:sequence>
                    <xs:element name="Poslovno_Ime"/>
                    <xs:element ref="a1:Adresa"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType abstract="true" name="TDrzavljanstvo"/>
    <xs:complexType name="TStrano_Drzavljanstvo">
        <xs:complexContent>
            <xs:extension base="a1:TDrzavljanstvo">
                <xs:sequence>
                    <xs:element name="Broj_Pasosa" type="a1:TBroj_Pasosa"></xs:element>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="TDomace_Drzavljanstvo">
        <xs:complexContent>
            <xs:extension base="a1:TDrzavljanstvo">
                <xs:sequence>
                    <xs:element name="Jmbg" type="a1:TJmbg"></xs:element>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:element name="Adresa">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Mjesto" type="xs:string"/>
                <xs:element name="Postanski_Broj" type="a1:TPostanski_Broj"></xs:element>
                <xs:element name="Ulica" type="xs:string"/>
                <xs:element name="Broj" type="xs:positiveInteger"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="TOsoba">
        <xs:sequence>
            <xs:element name="Ime" type="xs:string"/>
            <xs:element name="Prezime" type="xs:string"/>
            <xs:element ref="a1:Adresa"/>
            <xs:element name="Drzavljanstvo" type="a1:TDrzavljanstvo"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TDjelo">
        <xs:sequence>
            <xs:element name="Naslov" type="xs:string"/>
            <xs:element name="Vrsta_Djela" type="a1:Vrsta_Djela"/>
            <xs:element name="Forma_Zapisa" type="a1:Forma_Zapisa"/>
            <xs:element minOccurs="0" name="Podaci_Autor">
                <xs:complexType>
                    <xs:choice minOccurs="1">
                        <xs:element maxOccurs="unbounded" minOccurs="1" name="Poznati_Autor"
                                    type="a1:TAutor"/>
                        <xs:element default="true" name="Nepoznati_Autor" type="xs:boolean"/>
                    </xs:choice>
                </xs:complexType>
            </xs:element>
            <xs:element minOccurs="0" name="Stvoreno_U_Radnom_Odnosu" type="xs:boolean"/>
            <xs:element minOccurs="0" name="Nacin_koriscenja" type="xs:string"/>
            <xs:element minOccurs="0" name="Podaci_Originalno_Djelo">
                <xs:complexType>
                    <xs:sequence minOccurs="0">
                        <xs:element name="Naslov_Originalnog_Djela" type="xs:string"/>
                        <xs:choice>
                            <xs:element name="Poznati_Originalni_Autor" type="a1:TAutor"
                                        maxOccurs="unbounded" minOccurs="1"/>
                            <xs:element default="true" name="Nepoznati_Autor" type="xs:boolean"/>
                        </xs:choice>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType abstract="true" name="TAutor"/>
    <xs:complexType name="TZivi_Autor">
        <xs:complexContent>
            <xs:extension base="a1:TAutor">
                <xs:sequence>
                    <xs:element name="Podaci_Autor" type="a1:TOsoba"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="TPreminuli_Autor">
        <xs:complexContent>
            <xs:extension base="a1:TAutor">
                <xs:sequence>
                    <xs:element name="Ime" type="xs:string"/>
                    <xs:element name="Prezime" type="xs:string"/>
                    <xs:element name="Datum_Smrti" type="xs:date"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:simpleType name="Vrsta_Djela">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Pisano"/>
            <xs:enumeration value="Scensko"/>
            <xs:enumeration value="Likovno"/>
            <xs:enumeration value="Primjenjeno"/>
            <xs:enumeration value="Patent"/>
            <xs:enumeration value="Informacione Tehnologije"/>
            <xs:enumeration value="Naucna Teorija"/>
            <xs:enumeration value="Naucna Djelatnost"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="Forma_Zapisa">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Pisana"/>
            <xs:enumeration value="Audio"/>
            <xs:enumeration value="Vizuelna"/>
            <xs:enumeration value="AudioVizuelna"/>
            <xs:enumeration value="Opticki Disk"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="TJmbg">
        <xs:restriction base="xs:string">
            <xs:pattern value="[0-9]{13}"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="TBroj_Pasosa">
        <xs:restriction base="xs:string">
            <xs:pattern value="[a-zA-Z0-9]{3,20}"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="TEmail">
        <xs:restriction base="xs:string">
            <xs:pattern value="[^@]+@[^\.]+\..+"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="TBrojTelefona">
        <xs:restriction base="xs:string">
            <xs:pattern value="[+]?[0-9]{8,13}"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="TPostanski_Broj">
        <xs:restriction base="xs:positiveInteger">
            <xs:minInclusive value="1000"/>
            <xs:maxInclusive value="100000"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== Dragan2402/xml-veb-servisi/a1-backend/src/main/resources/data/schemas/ExampleA1-1.xml
<?xml version="1.0" encoding="UTF-8"?>
<obrazacA1 xmlns="http://euprava.euprava.com/model/a1Sertifikat"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://euprava.euprava.com/model/a1Sertifikat file:/C:/Users/draga/OneDrive/Dokumenti/4.%20Godina/XML%20i%20Web%20Servisi/Projekat/xml-veb-servisi/a1-backend/src/main/resources/data/schemas/a1_shema.xsd">
    <id>1</id>
    <Podnosilac xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="TFizicki_Podnosilac">
        <Telefon>0692402000</Telefon>
        <Email>draganmirkovic2402@yahoo.com</Email>
        <Podaci_Osoba>
            <Ime>gage</Ime>
            <Prezime>gage</Prezime>
            <Adresa>
                <Mjesto>Brcko</Mjesto>
                <Postanski_Broj>21000</Postanski_Broj>
                <Ulica>12321312</Ulica>
                <Broj>13</Broj>
            </Adresa>
            <Drzavljanstvo xsi:type="TStrano_Drzavljanstvo">
                <Broj_Pasosa>asdasdas</Broj_Pasosa>
            </Drzavljanstvo>
        </Podaci_Osoba>
    </Podnosilac>
    <Punomocnik>
        <Ime>Pero</Ime>
        <Prezime>Peric</Prezime>
        <Adresa>
            <Mjesto>Lokalac</Mjesto>
            <Postanski_Broj>1233</Postanski_Broj>
            <Ulica>Brza</Ulica>
            <Broj>123</Broj>
        </Adresa>
        <Drzavljanstvo xsi:type="TStrano_Drzavljanstvo">
            <Broj_Pasosa>asdasdas</Broj_Pasosa>
        </Drzavljanstvo>
    </Punomocnik>
    
    <Djelo>
        <Naslov>Gage Perez</Naslov>
        <Vrsta_Djela>Informacione Tehnologije</Vrsta_Djela>
        <Forma_Zapisa>Audio</Forma_Zapisa>

        <Stvoreno_U_Radnom_Odnosu>true</Stvoreno_U_Radnom_Odnosu>
        <Nacin_koriscenja>Laganica</Nacin_koriscenja>
        <Podaci_Originalno_Djelo>
            <Naslov_Originalnog_Djela>Macak Tosa</Naslov_Originalnog_Djela>

            <Poznati_Originalni_Autor xsi:type="TZivi_Autor">
                <Pseudonim_Znak_Autora>JJ</Pseudonim_Znak_Autora>
                <Podaci_Autor>
                    <Ime>Jovan</Ime>
                    <Prezime>Jovanovic</Prezime>
                    <Adresa>
                        <Mjesto>Kikinda</Mjesto>
                        <Postanski_Broj>2444</Postanski_Broj>
                        <Ulica>Neznana</Ulica>
                        <Broj>54</Broj>
                    </Adresa>
                    <Drzavljanstvo xsi:type="TDomace_Drzavljanstvo">
                        <Jmbg>1234567890123</Jmbg>
                    </Drzavljanstvo>
                </Podaci_Autor>
            </Poznati_Originalni_Autor>
            <Poznati_Originalni_Autor xsi:type="TPreminuli_Autor">
                <Pseudonim_Znak_Autora>KKK</Pseudonim_Znak_Autora>
                <Ime>Pokolica</Ime>
                <Prezime>Pokolicanin</Prezime>
                <Datum_Smrti>2022-11-23</Datum_Smrti>

            </Poznati_Originalni_Autor>
        </Podaci_Originalno_Djelo>
    </Djelo>
    <Potpis>gageleza</Potpis>
    <Sifra_Opisa>23232</Sifra_Opisa>
    <Sifra_Primjera>gagege</Sifra_Primjera>
    <Broj_Prijave>233</Broj_Prijave>
    <Datum_Podnosenja>2022-11-29</Datum_Podnosenja>
    <Status>Podnesen</Status>
</obrazacA1>
