=== Dragan2402/xml-veb-servisi/users-backend/src/main/resources/data/schemas/rjesenje.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://users.com/model/rjesenje"
    targetNamespace="http://users.com/model/rjesenje" elementFormDefault="qualified">

    <xs:element name="rjesenje">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="id">
                    <xs:simpleType>
                        <xs:restriction base="xs:long">
                            <xs:minInclusive value="1"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="id_zahtjeva">
                    <xs:simpleType>
                        <xs:restriction base="xs:long">
                            <xs:minInclusive value="1"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="tip_zahtjeva" type="TTip_Zahtjeva"/>
                <xs:element name="slucaj" type="TSlucaj"/>
                <xs:element name="datum" type="xs:date"/>
                <xs:element name="ime_sluzbenika" type="xs:string"/>
                <xs:element name="prezime_sluzbenika" type="xs:string"/>
                <xs:choice>
                    <xs:element minOccurs="1" name="sifra" type="xs:positiveInteger"/>
                    <xs:element minOccurs="1" name="obrazlozenje" type="xs:string"/>
                </xs:choice>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:simpleType name="TTip_Zahtjeva">
        <xs:restriction base="xs:string">
            <xs:enumeration value="A1"/>
            <xs:enumeration value="P1"/>
            <xs:enumeration value="Z1"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="TSlucaj">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Odbijanje"/>
            <xs:enumeration value="Odobravanje"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== Dragan2402/xml-veb-servisi/users-backend/src/main/resources/data/schemas/Example-Rjsenje.xml
<?xml version="1.0" encoding="UTF-8"?>
<rjesenje xmlns="http://users.com/model/rjesenje"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://users.com/model/rjesenje file:/C:/Users/draga/OneDrive/Dokumenti/4.%20Godina/XML%20i%20Web%20Servisi/Projekat/xml-veb-servisi/users-backend/src/main/resources/data/schemas/rjesenje.xsd">
    <id>1</id>
    <id_zahtjeva>123</id_zahtjeva>
    <tip_zahtjeva>A1</tip_zahtjeva>
    <slucaj>Odbijanje</slucaj>
    <datum>2023-02-23</datum>
    <ime_sluzbenika>Pero</ime_sluzbenika>
    <prezime_sluzbenika>Peric</prezime_sluzbenika>
    <obrazlozenje>Nedovoljna komunikacija</obrazlozenje>
</rjesenje>
